# Generated by Django 4.2.2 on 2023-08-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_user_id_sales_userid_sales_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
