# Generated by Django 4.2.2 on 2023-08-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sales_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='change_userid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='userproductid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
