# Generated by Django 4.2.2 on 2023-08-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sales_change_userid_sales_userproductid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sale',
        ),
    ]
