# Generated by Django 4.2.2 on 2023-08-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_sales_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_action',
            field=models.BooleanField(default=False),
        ),
    ]
