# Generated by Django 4.2.2 on 2023-08-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='daily_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
